version: "3"

services:

  server:

    build: server/
    command: python ./server.py
    ports:
      - 1234:1234
    networks:
      - net

  client:

    build: client/
    command: python ./client.py
    networks:
      - net


networks:
  net:
    driver: bridge
